name: antrobot
services:
  rpi:
    build: .
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    group_add:
      - dialout
      - video
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/i2c-1:/dev/i2c-1
      - /dev/video0:/dev/video0
    volumes:
      - /run/libcamera:/run/libcamera
